file_format: "1"
id: cygnus
name: Cygnus
type: shield
url: https://github.com/dactyl-keyboard/dactyl-keyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - cygnus_left
  - cygnus_right
